config/routes.rb
Cms::Application.routes.draw do
  
<<<<<<< HEAD
  resources :addresses

=======
>>>>>>> fe2516288b2b46312419d7289553e5acec78628c
  resources :profiles

  devise_for :users , path_names: {sign_in: "login" , sign_out: "logout"}  do
  
  
  resources :pages
  
  end

   root :to => 'firstpage#index'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
<<<<<<< HEAD
  belongs_to :user
  has_one :address
  attr_accessible :firstname, :lastname, :phoneno, :photo

  has_attached_file :photo , :styles => { :small => "150X150>" }
=======
  attr_accessible :firstname, :lastname, :phone , :photo
  belongs_to :user
 
  # validates :phone , :numericality => true , :if => :user_signed_in?
  has_attached_file :photo , :styles => { :small => "150X150>"}
>>>>>>> fe2516288b2b46312419d7289553e5acec78628c
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @profiles }
    end
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @profile = Profile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/new
  # GET /profiles/new.json
  def new
    @profile = Profile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/1/edit
  def edit
    @profile = Profile.find(params[:id])
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(params[:profile])

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render json: @profile, status: :created, location: @profile }
      else
        format.html { render action: "new" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /profiles/1
  # PUT /profiles/1.json
  def update
    @profile = Profile.find(params[:id])
<<<<<<< HEAD

    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
=======
    # redirect_to @profile
    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { render action: "show", notice: 'Profile was successfully updated.' }
>>>>>>> fe2516288b2b46312419d7289553e5acec78628c
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<<<<<<< HEAD
<%= form_for @profile , :html => {:multipart => true } do |f| %>
=======
<%= form_for (@profile ) do |f| %>
>>>>>>> fe2516288b2b46312419d7289553e5acec78628c
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br />
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
<<<<<<< HEAD
    <%= f.label :phoneno %><br />
    <%= f.number_field :phoneno %>
=======
    <%= f.label :phone %><br />
    <%= f.number_field :phone %>
>>>>>>> fe2516288b2b46312419d7289553e5acec78628c
  </div>
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.file_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<<<<<<< HEAD
<%= link_to 'Back', profile_path(current_user.profile) %>
=======
<%= link_to 'Back', profile_path(current_user.profile)   %>
>>>>>>> fe2516288b2b46312419d7289553e5acec78628c

app/views/profiles/index.html.erb
<<<<<<< HEAD
<h1>Listing profiles</h1>

<table>
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Phoneno</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @profiles.each do |profile| %>
  <tr>
    <td><%= profile.firstname %></td>
    <td><%= profile.lastname %></td>
    <td><%= profile.phoneno %></td>
    <td><%= profile.user %></td>
    <td><%= link_to 'Show', profile %></td>
    <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
    <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Profile', new_profile_path %>
=======
<% @profiles.each do |p| %>
 firstname:<%= p.firstname %>
 lastname:<%= p.lastname %>
 phone:<%= p.phone %>
 <!-- photo:<%= image_tag(p.photo) %> -->
 <% end %>
 <%= link_to "new" , new_profile_path %>
>>>>>>> fe2516288b2b46312419d7289553e5acec78628c

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<<<<<<< HEAD
<p id="notice "><%= notice %></p>
=======
<p id="notice"><%= notice %></p>
>>>>>>> fe2516288b2b46312419d7289553e5acec78628c

<p>
  <b>Firstname:</b>
  <%= @profile.firstname %>
</p>

<p>
  <b>Lastname:</b>
  <%= @profile.lastname %>
</p>

<p>
<<<<<<< HEAD
  <b>Phoneno:</b>
  <%= @profile.phoneno %>
</p>

<p>
  <b>Photo</b>
  <%= image_tag(@profile.photo.url(:small)) %></br ></br>


<%= link_to 'create location' , new_address_path %> </br >
=======
  <b>Phone:</b>
  <%= @profile.phone %>
</p>

<p>
  <b>Photo:</b>
  <%= image_tag(@profile.photo.url(:small)) %>
</p>


>>>>>>> fe2516288b2b46312419d7289553e5acec78628c
<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', pages_path %>